require 'quarto'
require 'quarto/tasks'

Quarto.configure do |config|
  config.author = 'Yasuhito Takamiya'
  config.title = 'Hello World'

  config.use :bundle
  config.use :git
  config.use :orgmode
  config.use :prince

  config.source_files = ['hello.org']
end
