* Trema 入門
** OpenFlow プログラミングフレームワーク Trema
*** セットアップ
Trema は Linux 上で動作し、Ubuntu 10.04 以降および Debian GNU/Linux
6.0 の 32 ビットおよび 64 ビット版での動作が保障されています。テストは
されていませんが、その他の Linux ディストリビューションでも基本的には動
作するはずです。本連載では、Ubuntu の最新バージョンである 11.04 (デスク
トップエディション 32 ビット版) を使います。

trema コマンドの実行には root 権限が必要です。まずは、sudo を使って
root 権限でコマンドを実行できるかどうか、sudo の設定ファイルを確認して
ください。

#+BEGIN_SRC
% sudo visudo
#+END_SRC

sudo ができることを確認したら、Trema が必要とする gcc などの外部ソフト
ウェアを次のようにインストールします。

#+BEGIN_SRC
% sudo apt-get install git gcc make ruby ruby-dev libpcap-dev libsqlite3-dev
#+END_SRC

次に Trema 本体をダウンロードします。Trema は GitHub 上で公開されており、
git を使って最新版が取得できます。

#+BEGIN_SRC
% git clone git://github.com/trema/trema.git
#+END_SRC

Trema のセットアップには、「make install」のようなシステム全体へインス
トールする手順は不要です。ビルドするだけで使い始めることができます。ビ
ルドは次のコマンドを実行するだけです。

#+BEGIN_SRC
% ./trema/build.rb
#+END_SRC

それでは早速、入門の定番 Hello, Trema! コントローラを Ruby で書いてみま
しょう。なお、本連載ではおもに Trema の Ruby ライブラリを使ったプログラ
ミングを取り上げます。C ライブラリを使ったプログラミングの例については、
Trema の src/examples/ ディレクトリ以下を参照してください。本連載で使っ
た Ruby コードに加えて、同じ内容の C コードをみつけることができます。

*** Trema のセットアップ
Trema は Linux 上で動作します。次のディストリビューションとバージョンで
の動作を保証しています。

 * Ubuntu 10.04 以降 (i386/amd64, デスクトップ版)
 * Debian GNU/Linux 6.0 (i386/amd64)

なお保証はしていませんが、RedHat などその他の Linux ディストリビューショ
ンでも動作するはずです。

Trema の提供する trema コマンドの実行には root 権限が必要です。まずは、
sudo を使って root 権限でコマンドを実行できるかどうか、sudo の設定ファ
イルを確認してください。

sudo が正しく設定できていることを確認したら、Trema のインストールや実行
に必要ないくつかのソフトウェアをインストールしましょう。

 * Ruby インタプリタ。Trema は Ruby と C で作成されていて、アプリケーショ
   ンの記述にも Ruby を使います。Trema では Ruby のバージョン 1.8.7 が
   必要です。1.8.6 以前のバージョンやバージョン 1.9 以降では今のところ
   動作しません。
 * Ruby のパッケージ管理システム RubyGems (https://rubygems.org/)
 * Trema 本体。本書は、Trema バージョン 0.3.0 を使用して執筆しています。
 * Trema のコンパイルに必要な gcc や make、およびいくつかのライブラリ。

開発に必要なのはこれだけです。それでは、Ubuntu のパッケージ管理システム
apt-get を使って必要なパッケージを次のようにインストールしてください。
もし他のディストリビューションを使いたい場合は、コマンド名とパッケージ
名を適宜読み替えください [fn:ubuntu]

[fn:ubuntu] Ubuntu 12.10 以降では Ruby のデフォルトバージョンが
Ruby1.9 になっているので、ruby, rubygems, ruby-dev をそれぞれ Trema が
サポートする ruby1.8, rubygems1.8, ruby-dev1.8 と読み替えてください。


#+BEGIN_SRC
% sudo apt-get install gcc make ruby rubygems ruby-dev irb libpcap-dev libsqlite3-dev
#+END_SRC

以上で Trema をインストールするための準備が整いました。続いて Trema を
インストールするには、RubyGems のパッケージで手軽にインストールする方法
と、最新のソースコードを取得して自分でビルドする方法があります。それぞ
れ説明していきましょう。

**** パッケージで手軽にインストールする場合

Trema は RubyGems を使って次のようにコマンド一発で簡単にインストールできます。

#+BEGIN_SRC
% gem install trema
#+END_SRC

RubyGems でインストールした場合、自動的に Trema のコマンド trema にパス
が通っているはずです。次のコマンドでバージョンが表示されればインストー
ルは成功です。

#+BEGIN_SRC
% trema --version
trema version 0.3.0
#+END_SRC

**** ソースコードから最新版をインストールする場合

最新版をインストールしたい人は、GitHub から自分でソースコードをダウンロー
ドしてビルドすることもできます。まず、次のように git を使って最新のソー
スコードを取得してください。

#+BEGIN_SRC
% git clone git://github.com/trema/trema.git
#+END_SRC

次のコマンドを実行すると、Trema が依存する RubyGems のパッケージが自動
的にインストールされます。

#+BEGIN_SRC
% cd trema
% gem install bundler
% bundle install
#+END_SRC

次のコマンドで Trema をダウンロードしたディレクトリ以下に Trema がイン
ストールされます。make install のようなシステム全体へのインストール手順
は不要ですので注意してください。

#+BEGIN_SRC
% ./build.rb
#+END_SRC

次のコマンドで trema コマンドが正しくインストールされたか確認してくださ
い。

#+BEGIN_SRC
% ./trema --version
trema version 0.3.0
#+END_SRC

もし必要あればこのディレクトリにパスを通し、trema コマンドが簡単に起動
できるようにしておいてください。

さあ、これで Trema による OpenFlow 開発環境が整いました。それでは早速、
入門の定番 Hello, World を Trema で書いてみましょう。
